const isMobile=/Mobi|Android/i.test(navigator.userAgent);
const form=document.getElementById('commentForm');
const commentsList=document.getElementById('commentsList');
const alertBox=document.getElementById('alert');
let comments=JSON.parse(localStorage.getItem('comments'))||[];
function escapeHtml(s){return String(s).replace(/[&<>"']/g,e=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[e]))}
function showAlert(msg,d=3000){if(!alertBox)return;alertBox.innerText=msg;alertBox.style.display='block';alertBox.style.opacity='1';setTimeout(()=>{alertBox.style.opacity='0';setTimeout(()=>alertBox.style.display='none',350)},d)}
function addCommentToDOM(name,message,prepend=false){const div=document.createElement('div');div.className='comment';div.innerHTML=`<strong>${escapeHtml(name)}</strong><p>${escapeHtml(message)}</p>`;if(prepend)commentsList.prepend(div);else commentsList.appendChild(div)}
comments.forEach(c=>{try{addCommentToDOM(c.name,c.message)}catch(e){console.error(e)}})
if(form)form.addEventListener('submit',e=>{e.preventDefault();const name=(document.getElementById('name')||{}).value?.trim()||'';const message=(document.getElementById('message')||{}).value?.trim()||'';if(!name||!message){showAlert('Por favor completa todos los campos');return}const comment={name,message};comments.unshift(comment);localStorage.setItem('comments',JSON.stringify(comments));addCommentToDOM(name,message,true);form.reset();showAlert('Comentario enviado correctamente')})
document.addEventListener('DOMContentLoaded',()=>{const t=document.getElementById('themeToggle');const savedTheme=localStorage.getItem('theme');if(savedTheme==='dark')document.body.classList.add('dark-mode');if(t)t.addEventListener('click',()=>{document.body.classList.toggle('dark-mode');localStorage.setItem('theme',document.body.classList.contains('dark-mode')?'dark':'light');showAlert(document.body.classList.contains('dark-mode')?'Modo oscuro activado':'Modo claro activado')});if(isMobile){document.querySelectorAll('a,button').forEach(el=>el.style.transition='none');document.body.style.fontSize='16px';document.querySelectorAll('h2').forEach(h=>h.style.fontSize='1.3rem');document.querySelectorAll('p').forEach(p=>p.style.lineHeight='1.5')}const cookieBanner=document.getElementById('cookieBanner'),acceptBtn=document.getElementById('acceptCookiesBtn'),dismissBtn=document.getElementById('dismissCookiesBtn');if(cookieBanner){const accepted=localStorage.getItem('cookiesAccepted');if(accepted!=='1'){cookieBanner.style.display='flex';cookieBanner.setAttribute('aria-hidden','false')}acceptBtn?.addEventListener('click',()=>{localStorage.setItem('cookiesAccepted','1');cookieBanner.style.display='none';cookieBanner.setAttribute('aria-hidden','true');showAlert('Gracias. Cookies aceptadas')});dismissBtn?.addEventListener('click',()=>{cookieBanner.style.display='none';cookieBanner.setAttribute('aria-hidden','true')})}})
